# Generated by Django 5.0.1 on 2024-01-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0002_sendarraymodal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendarraymodal',
            name='id',
        ),
        migrations.AlterField(
            model_name='sendarraymodal',
            name='Data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webScraper.webscrmodel'),
        ),
    ]
