# Generated by Django 5.0.1 on 2024-01-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0003_remove_sendarraymodal_id_alter_sendarraymodal_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sendArrayModal',
        ),
    ]
