# Generated by Django 5.0.1 on 2024-01-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0004_delete_sendarraymodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendArrayModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.ManyToManyField(to='webScraper.webscrmodel')),
            ],
        ),
    ]
